"""Markdown report formatter: generates the final report with trends, prompts, and sources."""

from src.prompt_writer.models import Prompt


def format_report(niche: str, prompts: list[Prompt]) -> str:
    """Format prompts into a markdown report.

    Args:
        niche: The niche analyzed.
        prompts: List of generated Prompt objects.

    Returns:
        Formatted markdown string ready to display or copy.
    """
    lines = [f"# TrendPrompt Report: {niche}\n"]

    # Group prompts by trend
    trends_seen: dict[str, list[Prompt]] = {}
    for prompt in prompts:
        trends_seen.setdefault(prompt.trend_title, []).append(prompt)

    for trend_title, trend_prompts in trends_seen.items():
        lines.append(f"## {trend_title}\n")

        for i, prompt in enumerate(trend_prompts, 1):
            lines.append(f"### Prompt {i}")
            lines.append(f"**Suggested product:** {prompt.suggested_product}\n")
            lines.append("```")
            lines.append(prompt.prompt_text)
            lines.append("```\n")

        # Sources
        all_sources = set()
        for p in trend_prompts:
            all_sources.update(p.sources)

        if all_sources:
            lines.append("**Sources:**")
            for src in sorted(all_sources):
                lines.append(f"- {src}")
            lines.append("")

    # Footer
    lines.append("---")
    lines.append("*Generated by TrendPrompt Engine*")

    return "\n".join(lines)
